# Generated by Django 6.1.1 on 2026-09-10 20:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calls', '0001_initial'),
        ('transcripts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task', models.TextField()),
                ('owner_name', models.CharField(blank=True, default='', max_length=255)),
                ('owner_type', models.CharField(blank=True, choices=[('agent', 'Agent'), ('customer', 'Customer'), ('supervisor', 'Supervisor'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('original_due_phrase', models.CharField(blank=True, default='', max_length=255)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUPPORTED', 'Supported'), ('PARTIAL', 'Partial'), ('UNSUPPORTED', 'Unsupported'), ('REVIEW', 'Review')], default='PENDING', max_length=16)),
                ('review_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActionItemEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intelligence.actionitem')),
                ('transcript_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcripts.transcriptsegment')),
            ],
        ),
        migrations.AddField(
            model_name='actionitem',
            name='evidence',
            field=models.ManyToManyField(blank=True, related_name='action_items', through='intelligence.ActionItemEvidence', to='transcripts.transcriptsegment'),
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('overall_confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('analysis_version', models.CharField(default='v1', max_length=64)),
                ('raw_extraction', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='calls.call')),
            ],
        ),
        migrations.AddField(
            model_name='actionitem',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='intelligence.analysis'),
        ),
        migrations.CreateModel(
            name='Blocker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('impact', models.TextField(blank=True, default='')),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUPPORTED', 'Supported'), ('PARTIAL', 'Partial'), ('UNSUPPORTED', 'Unsupported'), ('REVIEW', 'Review')], default='PENDING', max_length=16)),
                ('review_required', models.BooleanField(default=False)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockers', to='intelligence.analysis')),
            ],
        ),
        migrations.CreateModel(
            name='BlockerEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intelligence.blocker')),
                ('transcript_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcripts.transcriptsegment')),
            ],
        ),
        migrations.AddField(
            model_name='blocker',
            name='evidence',
            field=models.ManyToManyField(blank=True, related_name='blockers', through='intelligence.BlockerEvidence', to='transcripts.transcriptsegment'),
        ),
        migrations.CreateModel(
            name='ComplianceEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transcript_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcripts.transcriptsegment')),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('CONSENT', 'Consent'), ('CEASE_AND_DESIST', 'Cease and desist'), ('LEGAL_MENTION', 'Legal mention'), ('BANKRUPTCY', 'Bankruptcy'), ('WRONG_NUMBER', 'Wrong number'), ('SETTLEMENT_APPROVAL', 'Settlement approval'), ('OTHER', 'Other')], max_length=64)),
                ('severity', models.CharField(choices=[('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('RED', 'Red')], max_length=16)),
                ('observation', models.TextField()),
                ('rationale', models.TextField(blank=True, default='')),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('review_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_observations', to='intelligence.analysis')),
                ('evidence', models.ManyToManyField(blank=True, related_name='compliance_observations', through='intelligence.ComplianceEvidence', to='transcripts.transcriptsegment')),
            ],
        ),
        migrations.AddField(
            model_name='complianceevidence',
            name='compliance_observation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intelligence.complianceobservation'),
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUPPORTED', 'Supported'), ('PARTIAL', 'Partial'), ('UNSUPPORTED', 'Unsupported'), ('REVIEW', 'Review')], default='PENDING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='intelligence.analysis')),
            ],
        ),
        migrations.CreateModel(
            name='DecisionEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intelligence.decision')),
                ('transcript_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcripts.transcriptsegment')),
            ],
        ),
        migrations.AddField(
            model_name='decision',
            name='evidence',
            field=models.ManyToManyField(blank=True, related_name='decisions', through='intelligence.DecisionEvidence', to='transcripts.transcriptsegment'),
        ),
        migrations.CreateModel(
            name='EvidenceVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_type', models.CharField(max_length=64)),
                ('claim_id', models.UUIDField()),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUPPORTED', 'Supported'), ('PARTIAL', 'Partial'), ('UNSUPPORTED', 'Unsupported'), ('REVIEW', 'Review')], max_length=16)),
                ('score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('verifier_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='calls.call')),
            ],
        ),
        migrations.CreateModel(
            name='SentimentAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_sentiment', models.CharField(choices=[('POSITIVE', 'Positive'), ('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral'), ('MIXED', 'Mixed'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=16)),
                ('customer_sentiment', models.CharField(choices=[('POSITIVE', 'Positive'), ('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral'), ('MIXED', 'Mixed'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=16)),
                ('agent_sentiment', models.CharField(choices=[('POSITIVE', 'Positive'), ('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral'), ('MIXED', 'Mixed'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=16)),
                ('profanity_detected', models.BooleanField(default=False)),
                ('angry_customer_detected', models.BooleanField(default=False)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment', to='calls.call')),
            ],
        ),
        migrations.CreateModel(
            name='SentimentEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signal_type', models.CharField(blank=True, default='', max_length=64)),
                ('sentiment_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intelligence.sentimentanalysis')),
                ('transcript_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcripts.transcriptsegment')),
            ],
        ),
        migrations.AddField(
            model_name='sentimentanalysis',
            name='evidence',
            field=models.ManyToManyField(blank=True, related_name='sentiment_signals', through='intelligence.SentimentEvidence', to='transcripts.transcriptsegment'),
        ),
        migrations.AddConstraint(
            model_name='actionitemevidence',
            constraint=models.UniqueConstraint(fields=('action_item', 'transcript_segment'), name='unique_action_item_evidence'),
        ),
        migrations.AddConstraint(
            model_name='blockerevidence',
            constraint=models.UniqueConstraint(fields=('blocker', 'transcript_segment'), name='unique_blocker_evidence'),
        ),
        migrations.AddConstraint(
            model_name='complianceevidence',
            constraint=models.UniqueConstraint(fields=('compliance_observation', 'transcript_segment'), name='unique_compliance_evidence'),
        ),
        migrations.AddConstraint(
            model_name='decisionevidence',
            constraint=models.UniqueConstraint(fields=('decision', 'transcript_segment'), name='unique_decision_evidence'),
        ),
    ]
