# Generated by Django 6.1.1 on 2026-09-10 20:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_number', models.PositiveIntegerField()),
                ('speaker_label', models.CharField(max_length=128)),
                ('start_time_seconds', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('end_time_seconds', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='calls.call')),
            ],
            options={
                'ordering': ['line_number'],
                'indexes': [models.Index(fields=['call', 'line_number'], name='transcripts_call_id_a562b6_idx'), models.Index(fields=['call', 'speaker_label'], name='transcripts_call_id_c8795a_idx')],
                'constraints': [models.UniqueConstraint(fields=('call', 'line_number'), name='unique_call_line_number')],
            },
        ),
    ]
