# Generated by Django 6.1.1 on 2026-09-10 20:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calls', '0001_initial'),
        ('intelligence', '0001_initial'),
        ('transcripts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transcript_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcripts.transcriptsegment')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=128)),
                ('reason', models.TextField()),
                ('severity', models.CharField(choices=[('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('RED', 'Red')], max_length=16)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_REVIEW', 'In review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ESCALATED', 'Escalated')], default='OPEN', max_length=16)),
                ('source_type', models.CharField(blank=True, default='', max_length=64)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('reviewer_note', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_items', to='intelligence.analysis')),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_items', to='calls.call')),
                ('evidence', models.ManyToManyField(blank=True, related_name='review_items', through='reviews.ReviewEvidence', to='transcripts.transcriptsegment')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='reviewevidence',
            name='review_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.reviewitem'),
        ),
        migrations.AddConstraint(
            model_name='reviewevidence',
            constraint=models.UniqueConstraint(fields=('review_item', 'transcript_segment'), name='unique_review_evidence'),
        ),
    ]
