# Generated by Django 6.1.1 on 2026-09-10 20:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('domain', models.CharField(choices=[('debt_collection', 'Debt collection'), ('customer_support', 'Customer support'), ('sales', 'Sales'), ('internal', 'Internal'), ('other', 'Other')], max_length=64)),
                ('call_date', models.DateField()),
                ('recording_path', models.CharField(max_length=1024)),
                ('recording_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('TRANSCRIBING', 'Transcribing'), ('DIARIZING', 'Diarizing'), ('ANALYZING', 'Analyzing'), ('VERIFYING', 'Verifying'), ('COMPLIANCE_CHECK', 'Compliance check'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='UPLOADED', max_length=32)),
                ('error_message', models.TextField(blank=True, default='')),
                ('provider_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('TRANSCRIPTION', 'Transcription'), ('DIARIZATION', 'Diarization'), ('EXTRACTION', 'Extraction'), ('VERIFICATION', 'Verification'), ('COMPLIANCE', 'Compliance'), ('SENTIMENT', 'Sentiment'), ('FINALIZATION', 'Finalization')], max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='calls.call')),
            ],
            options={
                'ordering': ['started_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['user', 'created_at'], name='calls_call_user_id_3cf269_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['user', 'status'], name='calls_call_user_id_b465c6_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['call_date'], name='calls_call_call_da_9b05bc_idx'),
        ),
    ]
